rd_seed: 1
n_cls: 10
resolution: 64
ds_rate: 2
seq_length: -1
img_length: -1
log: /media/ymxlzgy/Data2/model_savedir/vi-net/log/housecat_pol

max_epoch : 40

optimizer:
  type : Adam
  lr   : 0.001
  betas: [0.5, 0.999]
  eps  : 0.000001
  weight_decay: 0


lr_scheduler:
  type: WarmupCosineLR
  max_iters: 200000
  warmup_factor: 0.001
  warmup_iters: 2000

loss:
  vp_weight: 100.0
  t_weight: 1.0
  s_weight: 1.0

train_dataset:
  data_dir: /media/ymxlzgy/FastData/housecat_v3
  sample_num: 2048
  random_rotate: True
  angle_range: 20

train_dataloader:
  bs: 24
  num_workers: 12
  shuffle: True
  drop_last: True
  pin_memory: False

test:
  sample_num: 2048
  data_dir: /media/ymxlzgy/FastData/housecat_v3
  log_dir: /media/ymxlzgy/Data2/model_savedir/vi-net/log/test


per_val: 10
per_write: 50
